@Library ('obTemplate@jira') _
pipeline {
    agent any
    environment {
        JIRA_URL = "https://auradevops.atlassian.net"
        JIRA_CREDENTIALS = credentials('jira-token')
    }
    stages {
        stage('Checkout repo'){
            steps{
                script {
                    checkoutProjectGit(
                        PROJECT_GITURL: 'https://git.dgpaysit.com/dgpays/dgpaysit/devops/jenkins/jenkins.git',
                        PROJECT_BRANCH: 'jira'
                    )
                    GIT_COMMIT_TAG_CURRENT = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
                }
            }
        }
        stage('Jira Transition Issue'){
            steps{
                script{
                    // 4 > cancelled , 3 > Ready for Test Deploy , 2 > Ready for Newman , 11 > To Do ,  21 > In Progress
                    //jiraTransitionIssue(transitionId:"4")
                    //jiraGetIssueKey(
                    //    COMMIT_ID: "${commitId}"
                    //)
                    echo "Test Deploy triggerlandı"
                }                
            }
        }        
    } 
}